### PR TITLE
Minecraft 1.12 port

### PR DESCRIPTION
**Pull request by asiekierka**

### CODE REVIEW

**Comment by CovertJaguar** [comment]
Well that was easy. Though, this is the wrong branch. I dare say the 1.11 version probably works in 1.12.

**Comment by asiekierka** [comment]
@CovertJaguar It doesn't, because a class name has changed. Also, there is no 1.12 branch for me to pull request to, is there?

**Comment by CovertJaguar** [comment]
Not yet, but I need to create a new dev environment to get it setup. I'll get around to it eventually.

**Comment by asiekierka** [comment]
I have been receiving multiple inquiries regarding this version's availability on CurseForge. Is anything planned in regards to this?

**Comment by SynexWolf** [comment]
Seems like that this mod hasn't been worked on since June 2017, The mod is using a MIT license so you could create a port version of the mod on curseforge yourself.

**Comment by asiekierka** [comment]
Won't do it unless I get explicit permission. CurseForge's culture is not ruled by legal matters alone.

**Comment by liach** [comment]
you can change the target version to 1.12.2 now

**Comment by SynexWolf** [comment]
@asiekierka, Have you tried to message @CovertJaguar on curseforge for permission? Cause it seems that they are active there...

**Comment by asiekierka** [comment]
I don't really want to push.

**Comment by liach** [comment]
Ah he's back.

**Pull request merged**
